### ISSUE TITLE
create our logo

### ISSUE THREAD

**Issue by juliabodera** [NLP-UG-2020-21/Heheszki_Project#21]

**Comment by malgomalgo** [comment]
![a2f9fa8c4281478a8855f0e8b31d5d4b](https://user-images.githubusercontent.com/81570370/160465623-a61d834d-261e-4b88-a33c-dfdd4ae379ed.png)

**Comment by AgataRozyckaUG** [comment]
![logo](https://user-images.githubusercontent.com/79416748/162897841-f5113262-8661-4b5e-a0fa-c075c55551bf.png)

**Comment by AgataRozyckaUG** [comment]
![Grafika_bez_nazwy](https://user-images.githubusercontent.com/79416748/168812208-b4bc833f-c7ea-4086-8d17-64e1685b83d4.png)
